version: '3.2'

services:
  front:
    build:
      context: frontend/cart/
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    expose:
      - "8080"
    networks:
      - elk

networks:
  elk:
    driver: bridge