version: "3"

services:
  jenkins:
    image: 'jenkinsci/blueocean'
    restart: unless-stopped
    user: root
    privileged: true
    ports:
      - '9090:8080'
    volumes:
      - '/home/ubuntu/docker/jenkins-data:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '$HOME:/home'
    container_name: 'jenkins'

  # redis:                     
  #  image: redis
  #  restart: always

  # spring:
  #   image: spring-backend
  #   container_name: backend
  #   build:
  #     context: ./backend/springboot
  #     dockerfile: backend.Dockerfile
  #   depends_on: 
  #     - redis
  #   ports:
  #     - 8081:8081

  # vue:
  #   image: vue-frontend
  #   container_name: frontend
  #   volumes:
  #     - ./key:/etc/nginx/key
  #   build:
  #     context: ./frontend/cart
  #     dockerfile: frontend.Dockerfile
  #   depends_on: 
  #     - spring
  #   ports:
  #     - 80:80
  #     - 443:443


    

